### ISSUE TITLE
issue1

### ISSUE THREAD

**Issue by EricCml** [EricCml/IssueCrawler#4]
test issue 1

- [x] #5
- [x] #6 
- [x] #7 
- [x] #8
- [x] rust-lang/cargo#6313
- [ ] https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_codegen_utils/lib.rs.html#7
- [ ] http://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_codegen_utils/lib.rs.html#7
- [x] //doc.rust-lang.org/nightly/nightly-rustc/src/rustc_codegen_utils/lib.rs.html/#7
- [ ] http://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_codegen_utils/lib.rs.html/#7
- [ ] https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc/traits/select.rs#3352
- [x] https://github.com/rust-lang/rust/blob/6bfa7d02d6713acd15ead20c199b808e85031f9e/src/librustc#3352 rust-lang/cargo#6313 rust-lang/carg#6313 #5 (#7)
- [x] (#7
- [x] [#7
- [x] {#7
- [x] <#7
- [x] /#7
- [x] .#7
- [ ] a#7
- [ ] 1#7
- [ ] _#7
- [x] -#7
- [ ] ddd
- [ ] rust-lang/rfcs#3323#issuecomment-1320747457
- [ ] ##7
----

* [ ] #7
